on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Lista de APIs'
        required: true
        options: ['production', 'staging', 'development']
        default: 'development'
