name: Build 
#In order for it to behave as intended, I have to use the following condition
#if: ${{ github.event.inputs.should_run_tests == "true" }}

#And not as you would expect from a boolean:
#if: ${{ github.event.inputs.should_run_tests }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      skip-tests:
        type: boolean
        description: Skip tests
      skip-tests2:
        type: boolean
        description: Skip tests

      #boolean:
       # type: boolean
        #description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
        
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
